services:
  autopage:
    image: npcdw/autopage:latest
    container_name: autopage
    user: root
    volumes:
      - "${PWD}/data/:/autopage/data"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'