services:
  autopage:
    image: npcdw/autopage:latest
    container_name: autopage
    user: root
    volumes:
      - "${PWD}/data/:/autopage/data"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'zh_CN.UTF-8'
      LC_ALL: 'zh_CN.UTF-8'
      LANGUAGE: 'zh_CN:zh'